name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'PHPStan'
                        run: composer phpstan

                    -
                        name: 'Bin Run'
                        run: bin/barista

                    -
                        name: 'Lint run on Single File'
                        run: bin/barista lint tests/latte-files/some-file.latte

                    -
                        name: 'Lint run on Single Directory'
                        run: bin/barista lint tests/latte-files/some-directory

                    -
                        name: 'Composer Validate'
                        run: composer validate

                    -
                        name: 'Coding Standard'
                        run: composer check-cs

                    -
                        name: 'Tests'
                        run: vendor/bin/phpunit

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}
